Vagrant.configure("2") do |config|

config.vm.box = "ubuntu/hirsute64"
  config.vm.hostname = "postgresdb-lab"
config.vm.network "forwarded_port", host_ip: "127.0.0.1", guest_ip: "127.0.0.1", guest: 5432, host: 5432,
    auto_correct: true

#to change vm name in Virtualbox
   config.vm.provider "virtualbox" do |v|
  v.name = "postgresql-lab"
end
config.vm.provision "shell",
    path: "postgresql_deploy.sh"
   end
