Vagrant.configure("2") do |config|

  #ssh block
  config.vm.provision "file", source: "~/.ssh/vagrant.pub", destination: "~/.ssh/authorized_keys"
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/vagrant"]
  config.ssh.insert_key = false
#####
  config.vm.box = "ubuntu/hirsute64"
  config.vm.hostname = "ansible-controller"
#config.vm.network "forwarded_port", host_ip: "127.0.0.1", guest_ip: "192.168", guest: 22, host: 2222,
  # config.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8265", ip: "192.168.0.13", guest: 22,
  
  config.vm.network "public_network", bridge: "eno1", ip: "192.168.0.23", guest: 22,
  auto_correct: true

#to change vm name in Virtualbox
   config.vm.provider "virtualbox" do |v|
 # Do not display the VirtualBox GUI when booting the machine
  v.gui = false
  v.name = "ansible-controller"
  # Customize the amount of memory on the VM:
  v.memory = 1024

end

config.vm.provision "shell",
    path: "ubuntu.sh"
end
