Vagrant.configure("2") do |config|

  config.vm.box = "centos/8"
  config.vm.hostname = "ansible-centos2"
#config.vm.network "forwarded_port", host_ip: "127.0.0.1", guest_ip: "192.168", guest: 22, host: 2222,
   config.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8265", ip: "192.168.0.15", guest: 22, host:2222,
   auto_correct: true

#to change vm name in Virtualbox
   config.vm.provider "virtualbox" do |v|
 # Do not display the VirtualBox GUI when booting the machine
  v.gui = false
  v.name = "ansible-centos-lab"
  # Customize the amount of memory on the VM:
  v.memory = 1024

end

config.vm.provision "shell",
    path: "centos.sh"
end
